FROM node:22-alpine

WORKDIR /app
COPY public ./public

COPY app-secure.js ./
COPY quiz-engine.js ./
COPY quizzes ./quizzes

RUN mkdir -p /data && chown node:node /data

USER node

EXPOSE 3000

CMD ["node", "app-secure.js"]
